/* Shared SEO constants and the OG-image URL builder.
 *
 * The dynamic image is generated by the edge function in `api/og.jsx`; here we
 * just assemble the URL its `title`/`subtitle` params drive. Kept apart from the
 * <Seo> component so both the component and any build-time tooling can import it
 * without pulling in React. */

// Canonical production origin. Used to make og:image/og:url absolute for the
// static fallback tags in index.html and as a safety net when a crawler reads
// meta before the app hydrates. Change this if the site moves domains.
export const SITE_URL = "https://gavinmcfarland.co.uk";

export const SITE_NAME = "Gavin McFarland";
export const DEFAULT_TITLE = "Gavin McFarland";
export const DEFAULT_DESCRIPTION =
  "Gavin McFarland — freelance developer building tools that take the friction out of building things. Currently working on Awenate.";

/* Build the /api/og URL for a page. `title` shows large; `subtitle` is the
   supporting line (usually the page's meta description). Returns a root-relative
   path — callers prepend an absolute origin where crawlers require one. */
export function ogImageUrl({ title, subtitle } = {}) {
  const params = new URLSearchParams();
  if (title) params.set("title", title);
  if (subtitle) params.set("subtitle", subtitle);
  const query = params.toString();
  return query ? `/api/og?${query}` : "/api/og";
}
