// Generated by generate-illustration.mjs
// Seed: 3059181 | Keywords: code | Main: code
// Dark mode: false
//
// Drop this component into your project and render it inside a container
// with a defined height (e.g. h-[400px] or h-full).

const CodeVisual = () => {
  return (
    <div className="relative w-full h-full">
      <div className="absolute bottom-14 left-14 w-44 h-32 border border-gray-100 animate-float" />
      <div className="absolute top-14 right-17 w-44 h-44 border border-gray-100" />

      {/* Main element: code */}
      <div className="absolute inset-0 m-auto w-[320px] flex items-center justify-center">
        <div className="bg-white border border-gray-100 shadow-2xl shadow-black/[0.04] overflow-hidden">
          <div className="p-6 flex flex-col">
            <div className="flex gap-2 mb-6">
              <div className="w-2.5 h-2.5 bg-gray-200" />
              <div className="w-2.5 h-2.5 bg-gray-200" />
              <div className="w-2.5 h-2.5 bg-gray-200" />
            </div>
            <div className="space-y-3">
              <div className="flex gap-2">
                <div className="w-24 h-2.5 bg-gray-200/60" />
              </div>
              <div className="flex gap-2">
                <div className="w-20 h-2.5 bg-gray-200" />
                <div className="w-10 h-2.5 bg-gray-100" />
                <div className="w-20 h-2.5 bg-gray-100" />
              </div>
              <div className="flex gap-2 ml-4">
                <div className="w-12 h-2.5 bg-gray-200" />
              </div>
              <div className="flex gap-2 ml-4">
                <div className="w-32 h-2.5 bg-gray-200/60" />
              </div>
              <div className="flex gap-2 ml-4">
                <div className="w-8 h-2.5 bg-gray-200/60" />
                <div className="w-12 h-2.5 bg-gray-100" />
                <div className="w-16 h-2.5 bg-gray-100" />
              </div>
              <div className="flex gap-2 ml-4">
                <div className="w-8 h-2.5 bg-gray-200/60" />
                <div className="w-14 h-2.5 bg-gray-100" />
                <div className="w-14 h-2.5 bg-gray-100" />
              </div>
              <div className="flex gap-2 ml-4">
                <div className="w-32 h-2.5 bg-gray-200/60" />
                <div className="w-28 h-2.5 bg-gray-100" />
              </div>
            </div>
            <div className="h-px w-full bg-gray-200 mt-6" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default CodeVisual;
